# Root directories
input_root: ../input/test
output_root: ../outputimg
model_name: gemini-2.5-flash-image
output_width: 1344
output_height: 768
api_key_path: gemini_api_key.txt

# Weather variants referencing standalone prompt files
variants:
  - name: sunny
    prompt_file: ../prompts/sunny.yaml
    creativity: 0.18
    fidelity: 0.82

  - name: sunset_backlight
    prompt_file: ../prompts/sunset_backlight.yaml
    creativity: 0.2
    fidelity: 0.8

  - name: heavy_rain
    prompt_file: ../prompts/heavy_rain.yaml
    creativity: 0.22
    fidelity: 0.75

  - name: rainy_night
    prompt_file: ../prompts/rainy_night.yaml
    creativity: 0.24
    fidelity: 0.78

  - name: dense_fog
    prompt_file: ../prompts/dense_fog.yaml
    creativity: 0.18
    fidelity: 0.82
