input_root: input/D52_glare_events
output_root: outputimg
seed: 20241023
jitter: 0.05  # small per-frame jitter for realism; set 0 for strict consistency

variants:
  - name: rain_medium
    type: rain
    params:
      density: 0.003
      length: 30
      angle_deg: -12
      droplet_density: 0.00005
      brightness: 0.94
      contrast: 0.94
  - name: fog_dense
    type: fog
    params:
      fog_intensity: 0.5
      visibility_bias: 0.1
      blur_sigma: 1.8
  - name: snow_light
    type: snow
    params:
      density: 0.001
      size_min: 1
      size_max: 2
      brightness: 1.02
